### PR TITLE
Update dotfiles

### PR DESCRIPTION
**Pull request by shinnn**
* remove unnecessary .npmignore
  * package.json has `files` field.
* use [container-based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) on Travis CI
* test on io.js and Node 0.12

### CODE REVIEW

**Comment by janraasch** [comment]
@shinnn we need `.npmignore` to overwrite the `.gitignore` file which would otherwise exclude the commpiled `index.js` file from the package.

**Comment by janraasch** [comment]
Otherwise this seems great. Could you ammend the commit and force push again?

**Comment by janraasch** [comment]
Maybe simply call it `Future-proof TravisCI`?

**Comment by janraasch** [comment]
Done with 2c7780021bf68f0cf9457a0af804d415ac465ae2

**Comment by shinnn** [comment]
Oh, Thanks and sorry for my laziness!

**Comment by janraasch** [comment]
Np, thank you for the pr.

**Pull request closed without merging**
